<?php
/**
 * Plugin Name: Product Reels
 * Description: Display shoppable vertical video reels linked to WooCommerce products — similar to Instagram/TikTok reels, but on your own store.
 * Version: 0.3.0
 * Author: Jv Secate
 * Text Domain: product-reels
 * Domain Path: /languages
 * Requires at least: 6.0
 * Requires PHP: 8.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'PRODUCT_REELS_VERSION', '0.3.0' );
define( 'PRODUCT_REELS_DIR', plugin_dir_path( __FILE__ ) );
define( 'PRODUCT_REELS_URL', plugin_dir_url( __FILE__ ) );

// Comments, translations and some strings were generated by LLMs.

/* -------------------------------------------------------------------------
 * FFmpeg binary management
 * ---------------------------------------------------------------------- */

/**
 * Return the path to the plugin-managed FFmpeg binary directory.
 * Stored inside wp-content/uploads so it survives plugin updates
 * and is writable without elevated permissions.
 */
function product_reels_bin_dir(): string {
	$upload = wp_upload_dir();
	return trailingslashit( $upload['basedir'] ) . 'product-reels-bin';
}

/**
 * Return the expected path of the plugin-managed binary for the current OS/arch.
 */
function product_reels_managed_binary(): string {
	$dir  = product_reels_bin_dir();
	$name = 'ffmpeg';
	if ( PHP_OS_FAMILY === 'Windows' ) {
		$name = 'ffmpeg.exe';
	}
	return $dir . DIRECTORY_SEPARATOR . $name;
}

/**
 * Detect the download URL for a static FFmpeg build that matches this server.
 * Returns [ 'url' => string, 'label' => string ] or null if unsupported.
 */
function product_reels_ffmpeg_download_info(): ?array {
	if ( PHP_OS_FAMILY === 'Windows' ) {
		return null; // Windows VPS not supported.
	}

	$arch = php_uname( 'm' ); // e.g. x86_64, aarch64, armv7l

	$base = 'https://johnvansickle.com/ffmpeg/releases/';

	if ( str_contains( $arch, 'x86_64' ) || str_contains( $arch, 'amd64' ) ) {
		return [
			'url'   => $base . 'ffmpeg-release-amd64-static.tar.xz',
			'arch'  => 'amd64',
			'label' => 'Linux x86_64 (amd64)',
		];
	}
	if ( str_contains( $arch, 'aarch64' ) || str_contains( $arch, 'arm64' ) ) {
		return [
			'url'   => $base . 'ffmpeg-release-arm64-static.tar.xz',
			'arch'  => 'arm64',
			'label' => 'Linux ARM64 (aarch64)',
		];
	}
	if ( str_contains( $arch, 'armv7' ) || str_contains( $arch, 'armhf' ) ) {
		return [
			'url'   => $base . 'ffmpeg-release-armhf-static.tar.xz',
			'arch'  => 'armhf',
			'label' => 'Linux ARMv7 (armhf)',
		];
	}

	return null; // Unsupported architecture.
}

/**
 * Resolve the active FFmpeg binary path, checking (in order):
 *   1. Plugin-managed binary in uploads/product-reels-bin/
 *   2. Manually entered path in settings
 *   3. Common system locations
 *   4. `which ffmpeg`
 */
function product_reels_ffmpeg_path(): string {
	static $path = null;
	if ( $path !== null ) {
		return $path;
	}

	// 1. Plugin-managed binary.
	$managed = product_reels_managed_binary();
	if ( file_exists( $managed ) && is_executable( $managed ) ) {
		$path = $managed;
		return $path;
	}

	// 2. Admin-specified path.
	$stored = get_option( 'product_reels_ffmpeg_path', '' );
	if ( $stored && is_executable( $stored ) ) {
		$path = $stored;
		return $path;
	}

	// 3. Common system locations.
	$candidates = [ '/usr/bin/ffmpeg', '/usr/local/bin/ffmpeg', '/opt/homebrew/bin/ffmpeg' ];
	foreach ( $candidates as $c ) {
		if ( is_executable( $c ) ) {
			$path = $c;
			return $path;
		}
	}

	// 4. PATH lookup.
	if ( function_exists( 'exec' ) ) {
		$out = [];
		exec( 'which ffmpeg 2>/dev/null', $out );
		if ( ! empty( $out[0] ) && is_executable( trim( $out[0] ) ) ) {
			$path = trim( $out[0] );
			return $path;
		}
	}

	$path = '';
	return $path;
}

function product_reels_has_ffmpeg(): bool {
	return product_reels_ffmpeg_path() !== '';
}

/**
 * Return a human-readable source label for the currently active binary.
 */
function product_reels_ffmpeg_source(): string {
	$active = product_reels_ffmpeg_path();
	if ( ! $active ) return 'none';
	if ( $active === product_reels_managed_binary() ) return 'managed';
	if ( $active === get_option( 'product_reels_ffmpeg_path', '' ) ) return 'manual';
	return 'system';
}

/* -------------------------------------------------------------------------
 * Main plugin class
 * ---------------------------------------------------------------------- */
class Product_Reels_Plugin {

	public function __construct() {
		add_action( 'plugins_loaded',              [ $this, 'load_textdomain' ] );
		add_action( 'init',                        [ $this, 'register_post_type' ] );
		add_action( 'add_meta_boxes',              [ $this, 'add_meta_boxes' ] );
		add_action( 'save_post_product_reel',      [ $this, 'save_reel' ] );
		add_action( 'wp_enqueue_scripts',          [ $this, 'enqueue_frontend_assets' ] );
		add_action( 'admin_enqueue_scripts',       [ $this, 'enqueue_admin_assets' ] );
		add_action( 'admin_notices',               [ $this, 'ffmpeg_admin_notice' ] );
		add_action( 'admin_menu',                  [ $this, 'add_settings_page' ] );
		add_action( 'admin_init',                  [ $this, 'register_settings' ] );
		add_action( 'wp_ajax_product_reels_generate_assets',     [ $this, 'ajax_generate_assets' ] );
		add_action( 'wp_ajax_product_reels_download_ffmpeg',      [ $this, 'ajax_download_ffmpeg' ] );
		add_action( 'wp_ajax_product_reels_download_ffmpeg_do',   [ $this, 'ajax_download_ffmpeg_do' ] );
		add_action( 'wp_ajax_product_reels_remove_ffmpeg',        [ $this, 'ajax_remove_ffmpeg' ] );
	}


	/* -----------------------------------------------------------------------
	 * Internationalization
	 * -------------------------------------------------------------------- */
	public function load_textdomain(): void {
		load_plugin_textdomain(
			'product-reels',
			false,
			dirname( plugin_basename( __FILE__ ) ) . '/languages'
		);
	}

	/* -----------------------------------------------------------------------
	 * Post type
	 * -------------------------------------------------------------------- */
	public function register_post_type(): void {
		register_post_type( 'product_reel', [
			'labels' => [
				'name'               => __( 'Product Reels', 'product-reels' ),
				'singular_name'      => __( 'Product Reel', 'product-reels' ),
				'add_new'            => __( 'Add New Reel', 'product-reels' ),
				'add_new_item'       => __( 'Add New Product Reel', 'product-reels' ),
				'edit_item'          => __( 'Edit Product Reel', 'product-reels' ),
				'new_item'           => __( 'New Product Reel', 'product-reels' ),
				'view_item'          => __( 'View Product Reel', 'product-reels' ),
				'search_items'       => __( 'Search Reels', 'product-reels' ),
				'not_found'          => __( 'No reels found.', 'product-reels' ),
				'not_found_in_trash' => __( 'No reels found in trash.', 'product-reels' ),
				'menu_name'          => __( 'Product Reels', 'product-reels' ),
			],
			'public'       => false,
			'show_ui'      => true,
			'menu_icon'    => 'dashicons-video-alt3',
			'supports'     => [ 'title', 'page-attributes' ],
			'show_in_rest' => true,
		] );
	}

	/* -----------------------------------------------------------------------
	 * Meta boxes
	 * -------------------------------------------------------------------- */
	public function add_meta_boxes(): void {
		add_meta_box(
			'product_reels_video',
			__( 'Video Source', 'product-reels' ),
			[ $this, 'render_video_metabox' ],
			'product_reel',
			'normal',
			'high'
		);
		add_meta_box(
			'product_reels_preview',
			__( 'Preview Clip & Thumbnail', 'product-reels' ),
			[ $this, 'render_preview_metabox' ],
			'product_reel',
			'normal',
			'default'
		);
		add_meta_box(
			'product_reels_product',
			__( 'Linked Product', 'product-reels' ),
			[ $this, 'render_product_metabox' ],
			'product_reel',
			'side',
			'default'
		);
		add_meta_box(
			'product_reels_help',
			__( 'How to use', 'product-reels' ),
			[ $this, 'render_help_metabox' ],
			'product_reel',
			'side',
			'low'
		);
	}

	/* -----------------------------------------------------------------------
	 * Metabox: Video source
	 * -------------------------------------------------------------------- */
	public function render_video_metabox( \WP_Post $post ): void {
		wp_nonce_field( 'product_reels_save', 'product_reels_nonce' );
		$source     = get_post_meta( $post->ID, '_pr_video_source', true ) ?: 'url';
		$url        = get_post_meta( $post->ID, '_pr_video_url', true );
		$upload_id  = absint( get_post_meta( $post->ID, '_pr_video_attachment_id', true ) );
		$upload_url = $upload_id ? wp_get_attachment_url( $upload_id ) : '';
		?>
		<div class="pr-metabox">
			<div class="pr-tabs" role="tablist">
				<button type="button" role="tab" class="pr-tab <?php echo $source === 'url' ? 'is-active' : ''; ?>"
					data-tab="url" aria-selected="<?php echo $source === 'url' ? 'true' : 'false'; ?>">
					🔗 <?php esc_html_e( 'Video URL', 'product-reels' ); ?>
				</button>
				<button type="button" role="tab" class="pr-tab <?php echo $source === 'upload' ? 'is-active' : ''; ?>"
					data-tab="upload" aria-selected="<?php echo $source === 'upload' ? 'true' : 'false'; ?>">
					⬆️ <?php esc_html_e( 'Upload File', 'product-reels' ); ?>
				</button>
			</div>
			<input type="hidden" name="_pr_video_source" id="pr_video_source" value="<?php echo esc_attr( $source ); ?>">

			<!-- URL panel -->
			<div class="pr-tab-panel <?php echo $source === 'url' ? 'is-active' : ''; ?>" data-panel="url">
				<div class="pr-field">
					<label for="pr_video_url">
						<?php esc_html_e( 'Video URL', 'product-reels' ); ?>
						<span class="pr-tooltip" data-tip="<?php esc_attr_e( 'Direct link to an .mp4, .webm or .mov file. Hosted video services (YouTube, Vimeo) are not supported — use a direct file URL.', 'product-reels' ); ?>">?</span>
					</label>
					<input type="url" id="pr_video_url" name="_pr_video_url"
						value="<?php echo esc_attr( $url ); ?>"
						placeholder="https://example.com/video.mp4"
						class="large-text">
				</div>
			</div>

			<!-- Upload panel -->
			<div class="pr-tab-panel <?php echo $source === 'upload' ? 'is-active' : ''; ?>" data-panel="upload">
				<div class="pr-field">
					<label>
						<?php esc_html_e( 'Video File', 'product-reels' ); ?>
						<span class="pr-tooltip" data-tip="<?php esc_attr_e( 'Upload an .mp4 or .webm file directly to the Media Library. Recommended format: MP4 (H.264).', 'product-reels' ); ?>">?</span>
					</label>
					<input type="hidden" name="_pr_video_attachment_id" id="pr_video_attachment_id" value="<?php echo esc_attr( $upload_id ?: '' ); ?>">
					<div class="pr-upload-area" id="pr_upload_area">
						<?php if ( $upload_url ) : ?>
							<video src="<?php echo esc_url( $upload_url ); ?>" controls muted class="pr-upload-preview"></video>
							<p class="pr-upload-filename"><?php echo esc_html( basename( get_attached_file( $upload_id ) ) ); ?></p>
						<?php else : ?>
							<div class="pr-upload-placeholder">
								<span class="dashicons dashicons-video-alt3"></span>
								<p><?php esc_html_e( 'No video selected', 'product-reels' ); ?></p>
							</div>
						<?php endif; ?>
					</div>
					<div class="pr-upload-actions">
						<button type="button" class="button" id="pr_upload_btn">
							<?php echo esc_html( $upload_id ? __( 'Change Video', 'product-reels' ) : __( 'Select / Upload Video', 'product-reels' ) ); ?>
						</button>
						<?php if ( $upload_id ) : ?>
							<button type="button" class="button pr-btn-danger" id="pr_remove_video_btn">
								<?php esc_html_e( 'Remove', 'product-reels' ); ?>
							</button>
						<?php endif; ?>
					</div>
				</div>
			</div>
		</div>
		<?php
	}

	/* -----------------------------------------------------------------------
	 * Metabox: Preview clip & thumbnail
	 * -------------------------------------------------------------------- */
	public function render_preview_metabox( \WP_Post $post ): void {
		$has_ffmpeg      = product_reels_has_ffmpeg();
		$thumb_id        = absint( get_post_meta( $post->ID, '_pr_thumbnail_id', true ) );
		$thumb_url       = $thumb_id ? wp_get_attachment_url( $thumb_id ) : '';
		$preview_id      = absint( get_post_meta( $post->ID, '_pr_preview_attachment_id', true ) );
		$preview_url     = $preview_id ? wp_get_attachment_url( $preview_id ) : '';
		$preview_enabled = get_post_meta( $post->ID, '_pr_preview_enabled', true );
		$preview_secs    = absint( get_post_meta( $post->ID, '_pr_preview_duration', true ) ) ?: 5;
		$thumb_offset    = absint( get_post_meta( $post->ID, '_pr_thumb_offset', true ) );
		?>
		<div class="pr-metabox">

			<?php if ( ! $has_ffmpeg ) : ?>
				<div class="pr-notice pr-notice--warning">
					<span class="dashicons dashicons-warning"></span>
					<?php esc_html_e( 'FFmpeg was not found on this server. Thumbnail and preview clip generation are unavailable. You can set a custom FFmpeg path in', 'product-reels' ); ?>
					<a href="<?php echo esc_url( admin_url( 'edit.php?post_type=product_reel&page=product-reels-settings' ) ); ?>"><?php esc_html_e( 'Product Reels Settings', 'product-reels' ); ?></a>.
				</div>
			<?php endif; ?>

			<!-- Thumbnail -->
			<div class="pr-section">
				<h4 class="pr-section-title">
					<?php esc_html_e( 'Thumbnail / Poster Image', 'product-reels' ); ?>
					<span class="pr-tooltip" data-tip="<?php esc_attr_e( 'The poster image is shown before the video loads, preventing a black screen. Recommended: generate from the video or upload your own.', 'product-reels' ); ?>">?</span>
				</h4>
				<div class="pr-thumb-row">
					<div class="pr-thumb-preview" id="pr_thumb_preview">
						<?php if ( $thumb_url ) : ?>
							<img src="<?php echo esc_url( $thumb_url ); ?>" alt="">
						<?php else : ?>
							<div class="pr-thumb-empty">
								<span class="dashicons dashicons-format-image"></span>
								<p><?php esc_html_e( 'No thumbnail', 'product-reels' ); ?></p>
							</div>
						<?php endif; ?>
					</div>
					<div class="pr-thumb-controls">
						<input type="hidden" name="_pr_thumbnail_id" id="pr_thumbnail_id" value="<?php echo esc_attr( $thumb_id ?: '' ); ?>">
						<?php if ( $has_ffmpeg ) : ?>
							<div class="pr-field pr-field--inline">
								<label for="pr_thumb_offset">
									<?php esc_html_e( 'Extract frame at (seconds)', 'product-reels' ); ?>
									<span class="pr-tooltip" data-tip="<?php esc_attr_e( 'Which second of the video to use as the thumbnail frame.', 'product-reels' ); ?>">?</span>
								</label>
								<input type="number" id="pr_thumb_offset" name="_pr_thumb_offset" value="<?php echo esc_attr( $thumb_offset ); ?>" min="0" step="1" style="width:80px">
							</div>
							<button type="button" class="button button-primary pr-generate-btn" id="pr_gen_thumb_btn" data-action="thumbnail" data-post="<?php echo esc_attr( $post->ID ); ?>">
								<span class="dashicons dashicons-update"></span>
								<?php esc_html_e( 'Generate from video', 'product-reels' ); ?>
							</button>
						<?php endif; ?>
						<button type="button" class="button" id="pr_upload_thumb_btn">
							<span class="dashicons dashicons-upload"></span>
							<?php esc_html_e( 'Upload image', 'product-reels' ); ?>
						</button>
						<?php if ( $thumb_id ) : ?>
							<button type="button" class="button pr-btn-link" id="pr_remove_thumb_btn">
								<?php esc_html_e( 'Remove thumbnail', 'product-reels' ); ?>
							</button>
						<?php endif; ?>
						<div class="pr-spinner" id="pr_thumb_spinner" style="display:none"></div>
						<div class="pr-feedback" id="pr_thumb_feedback"></div>
					</div>
				</div>
			</div>

			<!-- Preview clip -->
			<div class="pr-section">
				<h4 class="pr-section-title">
					<?php esc_html_e( 'Preview Clip', 'product-reels' ); ?>
					<span class="pr-badge pr-badge--optional"><?php esc_html_e( 'Optional', 'product-reels' ); ?></span>
					<span class="pr-tooltip" data-tip="<?php esc_attr_e( 'A short, muted, compressed version of the video that autoplays in the reel card. The full video is only loaded when the user clicks.', 'product-reels' ); ?>">?</span>
				</h4>
				<?php if ( $has_ffmpeg ) : ?>
					<div class="pr-field pr-field--checkbox">
						<label>
							<input type="checkbox" name="_pr_preview_enabled" id="pr_preview_enabled" value="1" <?php checked( $preview_enabled, '1' ); ?>>
							<?php esc_html_e( 'Enable preview clip for this reel', 'product-reels' ); ?>
						</label>
					</div>
					<div class="pr-preview-options" id="pr_preview_options" <?php echo $preview_enabled ? '' : 'style="display:none"'; ?>>
						<div class="pr-field pr-field--inline">
							<label for="pr_preview_duration">
								<?php esc_html_e( 'Clip duration (seconds)', 'product-reels' ); ?>
								<span class="pr-tooltip" data-tip="<?php esc_attr_e( 'How many seconds from the start of the video to include in the preview clip. 3–8 seconds works best.', 'product-reels' ); ?>">?</span>
							</label>
							<input type="number" id="pr_preview_duration" name="_pr_preview_duration"
								value="<?php echo esc_attr( $preview_secs ); ?>"
								min="1" max="30" step="1" style="width:80px">
						</div>
						<div class="pr-field">
							<input type="hidden" name="_pr_preview_attachment_id" id="pr_preview_attachment_id" value="<?php echo esc_attr( $preview_id ?: '' ); ?>">
							<?php if ( $preview_url ) : ?>
								<div class="pr-preview-current">
									<video src="<?php echo esc_url( $preview_url ); ?>" muted autoplay loop playsinline class="pr-upload-preview" style="max-width:120px"></video>
									<span class="pr-preview-label"><?php esc_html_e( 'Current preview clip', 'product-reels' ); ?></span>
								</div>
							<?php endif; ?>
							<button type="button" class="button button-primary pr-generate-btn" id="pr_gen_preview_btn" data-action="preview" data-post="<?php echo esc_attr( $post->ID ); ?>">
								<span class="dashicons dashicons-update"></span>
								<?php esc_html_e( 'Generate preview clip', 'product-reels' ); ?>
							</button>
							<div class="pr-spinner" id="pr_preview_spinner" style="display:none"></div>
							<div class="pr-feedback" id="pr_preview_feedback"></div>
						</div>
					</div>
				<?php else : ?>
					<p class="pr-muted"><?php esc_html_e( 'Preview clip generation requires FFmpeg. See the warning above.', 'product-reels' ); ?></p>
				<?php endif; ?>
			</div>
		</div>
		<?php
	}

	/* -----------------------------------------------------------------------
	 * Metabox: Linked product
	 * -------------------------------------------------------------------- */
	public function render_product_metabox( \WP_Post $post ): void {
		$product_id = absint( get_post_meta( $post->ID, '_pr_product_id', true ) );
		$product    = $product_id && function_exists( 'wc_get_product' ) ? wc_get_product( $product_id ) : null;
		?>
		<div class="pr-metabox pr-metabox--side">
			<?php if ( ! function_exists( 'wc_get_product' ) ) : ?>
				<div class="pr-notice pr-notice--info">
					<?php esc_html_e( 'WooCommerce is not active. Product linking is unavailable.', 'product-reels' ); ?>
				</div>
			<?php else : ?>
				<div class="pr-field">
					<label for="pr_product_id">
						<?php esc_html_e( 'WooCommerce Product ID', 'product-reels' ); ?>
						<span class="pr-tooltip" data-tip="<?php esc_attr_e( 'The numeric ID of the product to link to this reel. Find it in Products → hover over a product → look for ID in the URL.', 'product-reels' ); ?>">?</span>
					</label>
					<input type="number" id="pr_product_id" name="_pr_product_id"
						value="<?php echo esc_attr( $product_id ?: '' ); ?>"
						placeholder="e.g. 42" min="1" class="small-text">
				</div>
				<?php if ( $product ) : ?>
					<div class="pr-product-preview">
						<?php echo $product->get_image( [ 48, 48 ] ); ?>
						<div>
							<strong><?php echo esc_html( $product->get_name() ); ?></strong>
							<span><?php echo wp_kses_post( $product->get_price_html() ); ?></span>
						</div>
					</div>
				<?php elseif ( $product_id ) : ?>
					<p class="pr-muted">⚠️ <?php esc_html_e( 'Product not found. Double-check the ID.', 'product-reels' ); ?></p>
				<?php endif; ?>
			<?php endif; ?>
		</div>
		<?php
	}

	/* -----------------------------------------------------------------------
	 * Metabox: Help
	 * -------------------------------------------------------------------- */
	public function render_help_metabox( \WP_Post $post ): void {
		?>
		<div class="pr-metabox pr-metabox--side pr-help">
			<ol class="pr-help-steps">
				<li><?php esc_html_e( 'Give the reel a title (used in the admin only).', 'product-reels' ); ?></li>
				<li><?php esc_html_e( 'Add a video — either paste a direct URL or upload a file.', 'product-reels' ); ?></li>
				<li><?php esc_html_e( 'Generate a thumbnail so visitors never see a black screen.', 'product-reels' ); ?></li>
				<li><?php esc_html_e( 'Optionally generate a short preview clip to autoplay on the card.', 'product-reels' ); ?></li>
				<li><?php esc_html_e( 'Link a WooCommerce product to show a buy button below the reel.', 'product-reels' ); ?></li>
				<li>
					<?php
					printf(
						/* translators: %s: PHP function name */
						esc_html__( 'Display the reels on any page by calling %s in your theme.', 'product-reels' ),
						'<code>product_reels_render_section()</code>'
					);
					?>
				</li>
			</ol>
			<p><a href="<?php echo esc_url( admin_url( 'edit.php?post_type=product_reel&page=product-reels-settings' ) ); ?>">
				⚙️ <?php esc_html_e( 'Plugin Settings', 'product-reels' ); ?>
			</a></p>
		</div>
		<?php
	}

	/* -----------------------------------------------------------------------
	 * Save reel meta
	 * -------------------------------------------------------------------- */
	public function save_reel( int $post_id ): void {
		if ( ! isset( $_POST['product_reels_nonce'] ) ||
			! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['product_reels_nonce'] ) ), 'product_reels_save' ) ) {
			return;
		}
		if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
			return;
		}
		if ( ! current_user_can( 'edit_post', $post_id ) ) {
			return;
		}

		$fields = [
			'_pr_video_source'          => 'sanitize_text_field',
			'_pr_video_url'             => 'esc_url_raw',
			'_pr_video_attachment_id'   => 'absint',
			'_pr_product_id'            => 'absint',
			'_pr_thumbnail_id'          => 'absint',
			'_pr_thumb_offset'          => 'absint',
			'_pr_preview_attachment_id' => 'absint',
			'_pr_preview_duration'      => 'absint',
		];

		foreach ( $fields as $key => $sanitizer ) {
			if ( isset( $_POST[ $key ] ) ) {
				$raw   = wp_unslash( $_POST[ $key ] );
				$value = $sanitizer( $raw );
				update_post_meta( $post_id, $key, $value );
			}
		}

		// Checkbox: preview enabled.
		$preview_enabled = isset( $_POST['_pr_preview_enabled'] ) ? '1' : '0';
		update_post_meta( $post_id, '_pr_preview_enabled', $preview_enabled );
	}

	/* -----------------------------------------------------------------------
	 * AJAX: Generate thumbnail or preview clip via FFmpeg
	 * -------------------------------------------------------------------- */
	public function ajax_generate_assets(): void {
		check_ajax_referer( 'product_reels_admin', 'nonce' );

		if ( ! current_user_can( 'edit_posts' ) ) {
			wp_send_json_error( [ 'message' => __( 'Permission denied.', 'product-reels' ) ] );
		}

		$post_id = absint( $_POST['post_id'] ?? 0 );
		$action  = sanitize_key( $_POST['generate'] ?? '' );

		if ( ! $post_id || ! in_array( $action, [ 'thumbnail', 'preview' ], true ) ) {
			wp_send_json_error( [ 'message' => __( 'Invalid request.', 'product-reels' ) ] );
		}

		if ( ! product_reels_has_ffmpeg() ) {
			wp_send_json_error( [ 'message' => __( 'FFmpeg is not available on this server.', 'product-reels' ) ] );
		}

		// Resolve video file path.
		$source = get_post_meta( $post_id, '_pr_video_source', true );
		if ( $source === 'upload' ) {
			$att_id    = absint( get_post_meta( $post_id, '_pr_video_attachment_id', true ) );
			$video_path = $att_id ? get_attached_file( $att_id ) : '';
		} else {
			$video_url  = get_post_meta( $post_id, '_pr_video_url', true );
			$video_path = $video_url ? $this->fetch_remote_video( $video_url ) : '';
		}

		if ( ! $video_path || ! file_exists( $video_path ) ) {
			wp_send_json_error( [ 'message' => __( 'Video file not found. Please save the reel first.', 'product-reels' ) ] );
		}

		$upload_dir = wp_upload_dir();
		$dest_dir   = trailingslashit( $upload_dir['path'] );
		$ffmpeg     = product_reels_ffmpeg_path();
		$slug       = 'pr-' . $post_id . '-' . time();

		if ( $action === 'thumbnail' ) {
			$offset   = absint( get_post_meta( $post_id, '_pr_thumb_offset', true ) );
			$out_file = $dest_dir . $slug . '-thumb.jpg';
			$cmd      = sprintf(
				'%s -y -ss %d -i %s -frames:v 1 -q:v 2 %s 2>&1',
				escapeshellarg( $ffmpeg ),
				$offset,
				escapeshellarg( $video_path ),
				escapeshellarg( $out_file )
			);
			shell_exec( $cmd );
			if ( ! file_exists( $out_file ) ) {
				wp_send_json_error( [ 'message' => __( 'FFmpeg failed to generate the thumbnail.', 'product-reels' ) ] );
			}
			$att_id = $this->sideload_file( $out_file, $post_id, 'jpg' );
			if ( is_wp_error( $att_id ) ) {
				wp_send_json_error( [ 'message' => $att_id->get_error_message() ] );
			}
			// Remove old thumbnail attachment if different.
			$old_id = absint( get_post_meta( $post_id, '_pr_thumbnail_id', true ) );
			if ( $old_id && $old_id !== $att_id ) {
				wp_delete_attachment( $old_id, true );
			}
			update_post_meta( $post_id, '_pr_thumbnail_id', $att_id );
			wp_send_json_success( [
				'attachment_id' => $att_id,
				'url'           => wp_get_attachment_url( $att_id ),
				'message'       => __( 'Thumbnail generated!', 'product-reels' ),
			] );
		}

		if ( $action === 'preview' ) {
			$duration = absint( get_post_meta( $post_id, '_pr_preview_duration', true ) ) ?: 5;
			$out_file = $dest_dir . $slug . '-preview.mp4';
			// Trim + strip audio + scale to max 480px wide + high quality compression.
			$cmd = sprintf(
				'%s -y -i %s -t %d -an -vf "scale=\'min(480,iw)\':-2" -c:v libx264 -preset fast -crf 28 -movflags +faststart %s 2>&1',
				escapeshellarg( $ffmpeg ),
				escapeshellarg( $video_path ),
				$duration,
				escapeshellarg( $out_file )
			);
			shell_exec( $cmd );
			if ( ! file_exists( $out_file ) ) {
				wp_send_json_error( [ 'message' => __( 'FFmpeg failed to generate the preview clip.', 'product-reels' ) ] );
			}
			$att_id = $this->sideload_file( $out_file, $post_id, 'mp4' );
			if ( is_wp_error( $att_id ) ) {
				wp_send_json_error( [ 'message' => $att_id->get_error_message() ] );
			}
			$old_id = absint( get_post_meta( $post_id, '_pr_preview_attachment_id', true ) );
			if ( $old_id && $old_id !== $att_id ) {
				wp_delete_attachment( $old_id, true );
			}
			update_post_meta( $post_id, '_pr_preview_attachment_id', $att_id );
			wp_send_json_success( [
				'attachment_id' => $att_id,
				'url'           => wp_get_attachment_url( $att_id ),
				'message'       => sprintf( __( 'Preview clip generated (%ds)!', 'product-reels' ), $duration ),
			] );
		}
	}

	/* -----------------------------------------------------------------------
	 * Helpers
	 * -------------------------------------------------------------------- */

	/**
	 * Download a remote video to a temp file and return the local path.
	 */
	private function fetch_remote_video( string $url ): string {
		$tmp = download_url( $url );
		if ( is_wp_error( $tmp ) ) {
			return '';
		}
		// Rename with extension so FFmpeg can detect the format.
		$ext  = pathinfo( parse_url( $url, PHP_URL_PATH ), PATHINFO_EXTENSION ) ?: 'mp4';
		$dest = $tmp . '.' . $ext;
		rename( $tmp, $dest );
		return $dest;
	}

	/**
	 * Register a local file as a Media Library attachment and delete the temp file.
	 *
	 * @return int|\WP_Error
	 */
	private function sideload_file( string $file, int $post_id, string $ext ) {
		require_once ABSPATH . 'wp-admin/includes/file.php';
		require_once ABSPATH . 'wp-admin/includes/media.php';
		require_once ABSPATH . 'wp-admin/includes/image.php';

		$upload_dir  = wp_upload_dir();
		$upload_path = trailingslashit( $upload_dir['path'] );
		$filename    = basename( $file );
		$new_path    = $upload_path . $filename;

		if ( $file !== $new_path ) {
			if ( ! copy( $file, $new_path ) ) {
				return new \WP_Error( 'copy_failed', __( 'Could not copy generated file to uploads directory.', 'product-reels' ) );
			}
			@unlink( $file );
		}

		$filetype = wp_check_filetype( $filename, null );
		$att_id   = wp_insert_attachment( [
			'guid'           => trailingslashit( $upload_dir['url'] ) . $filename,
			'post_mime_type' => $filetype['type'],
			'post_title'     => preg_replace( '/\.[^.]+$/', '', $filename ),
			'post_content'   => '',
			'post_status'    => 'inherit',
		], $new_path, $post_id );

		if ( is_wp_error( $att_id ) ) {
			return $att_id;
		}

		$metadata = wp_generate_attachment_metadata( $att_id, $new_path );
		wp_update_attachment_metadata( $att_id, $metadata );

		return $att_id;
	}

	/* -----------------------------------------------------------------------
	 * Assets
	 * -------------------------------------------------------------------- */
	public function enqueue_frontend_assets(): void {
		wp_enqueue_style( 'product-reels', PRODUCT_REELS_URL . 'assets/product-reels.css', [], PRODUCT_REELS_VERSION );
		wp_enqueue_script( 'product-reels', PRODUCT_REELS_URL . 'assets/product-reels.js', [], PRODUCT_REELS_VERSION, true );
	}

	public function enqueue_admin_assets( string $hook ): void {
		$screen = get_current_screen();
		if ( ! $screen || $screen->post_type !== 'product_reel' ) {
			return;
		}		wp_enqueue_media();
		wp_enqueue_style( 'product-reels-admin', PRODUCT_REELS_URL . 'assets/product-reels-admin.css', [], PRODUCT_REELS_VERSION );
		wp_enqueue_script( 'product-reels-admin', PRODUCT_REELS_URL . 'assets/product-reels-admin.js', [ 'jquery', 'wp-util' ], PRODUCT_REELS_VERSION, true );
		wp_localize_script( 'product-reels-admin', 'ProductReels', [
			'ajaxurl' => admin_url( 'admin-ajax.php' ),
			'nonce'   => wp_create_nonce( 'product_reels_admin' ),
			'i18n'    => [
				'selectVideo'     => __( 'Select Video', 'product-reels' ),
				'useVideo'        => __( 'Use this video', 'product-reels' ),
				'selectImage'     => __( 'Select Thumbnail Image', 'product-reels' ),
				'useImage'        => __( 'Use this image', 'product-reels' ),
				'generating'      => __( 'Generating…', 'product-reels' ),
				'savingFirst'     => __( 'Please save the post before generating assets.', 'product-reels' ),
				'noVideo'         => __( 'Please add a video URL or upload a video first, then save.', 'product-reels' ),
				'noVideoSelected' => __( 'No video selected', 'product-reels' ),
				'changeVideo'     => __( 'Change Video', 'product-reels' ),
				'selectUploadVideo' => __( 'Select / Upload Video', 'product-reels' ),
				'noThumbnail'     => __( 'No thumbnail', 'product-reels' ),
				'removeThumbnail' => __( 'Remove thumbnail', 'product-reels' ),
				'currentPreviewClip' => __( 'Current preview clip', 'product-reels' ),
				'error'           => __( 'Error.', 'product-reels' ),
				'serverErrorTryAgain' => __( 'Server error. Please try again.', 'product-reels' ),
				'downloading'     => __( '⏳ Downloading…', 'product-reels' ),
				'downloadStatus'  => __( 'Connecting to johnvansickle.com and downloading static FFmpeg binary (~40 MB)…', 'product-reels' ),
				'reloading'       => __( 'Reloading…', 'product-reels' ),
				'unknownError'    => __( 'Unknown error.', 'product-reels' ),
				'retryDownload'   => __( '⬇️ Retry download', 'product-reels' ),
				'downloadTimedOut' => __( 'Server error (HTTP %d). The download may have timed out — try increasing PHP max_execution_time.', 'product-reels' ),
				'removeFfmpegConfirm' => __( 'Remove the plugin-managed FFmpeg binary? You can re-download it at any time.', 'product-reels' ),
				'removing'        => __( 'Removing…', 'product-reels' ),
				'errorRemovingBinary' => __( 'Error removing binary.', 'product-reels' ),
				'serverError'     => __( 'Server error.', 'product-reels' ),
			],
		] );
	}

	/* -----------------------------------------------------------------------
	 * Admin notice if FFmpeg missing
	 * -------------------------------------------------------------------- */
	public function ffmpeg_admin_notice(): void {
		$screen = get_current_screen();
		if ( ! $screen || $screen->post_type !== 'product_reel' ) {
			return;
		}
		if ( ! product_reels_has_ffmpeg() ) {
			echo '<div class="notice notice-warning is-dismissible"><p>';
			printf(
				/* translators: %s: settings page link */
				esc_html__( '⚠️ Product Reels: FFmpeg was not detected on this server. Thumbnail and preview generation are disabled. %s', 'product-reels' ),
				'<a href="' . esc_url( admin_url( 'edit.php?post_type=product_reel&page=product-reels-settings' ) ) . '">' . esc_html__( 'Set a custom FFmpeg path →', 'product-reels' ) . '</a>'
			);
			echo '</p></div>';
		}
	}

	/* -----------------------------------------------------------------------
	 * Settings page
	 * -------------------------------------------------------------------- */
	public function add_settings_page(): void {
		add_submenu_page(
			'edit.php?post_type=product_reel',
			__( 'Product Reels Settings', 'product-reels' ),
			__( 'Settings', 'product-reels' ),
			'manage_options',
			'product-reels-settings',
			[ $this, 'render_settings_page' ]
		);
	}

	public function register_settings(): void {
		register_setting( 'product_reels_settings', 'product_reels_ffmpeg_path', [
			'type'              => 'string',
			'sanitize_callback' => 'sanitize_text_field',
			'default'           => '',
		] );
	}

	public function render_settings_page(): void {
		$has_ffmpeg    = product_reels_has_ffmpeg();
		$active_path   = product_reels_ffmpeg_path();
		$source        = product_reels_ffmpeg_source();
		$managed_path  = product_reels_managed_binary();
		$managed_exists = file_exists( $managed_path );
		$download_info = product_reels_ffmpeg_download_info();
		$bin_dir       = product_reels_bin_dir();
		$bin_writable  = ( is_dir( $bin_dir ) && is_writable( $bin_dir ) )
		              || ( ! is_dir( $bin_dir ) && is_writable( dirname( $bin_dir ) ) );
		?>
		<div class="wrap pr-settings-wrap">
			<h1>⚙️ <?php esc_html_e( 'Product Reels Settings', 'product-reels' ); ?></h1>

			<!-- ================================================================
			     FFmpeg status card
			     ============================================================ -->
			<div class="pr-settings-card">
				<h2><?php esc_html_e( 'FFmpeg', 'product-reels' ); ?></h2>
				<p class="pr-settings-desc">
					<?php esc_html_e( 'FFmpeg is required for thumbnail extraction and preview clip generation. It is never bundled in the plugin zip — instead you can download a static binary directly to your server with one click, or point to an existing installation.', 'product-reels' ); ?>
				</p>

				<!-- Status banner -->
				<?php if ( $has_ffmpeg ) : ?>
					<div class="pr-status-banner pr-status-banner--ok">
						<span class="pr-status-icon">✔</span>
						<div>
							<strong><?php esc_html_e( 'FFmpeg is active', 'product-reels' ); ?></strong>
							<span class="pr-status-meta">
								<?php echo esc_html( $active_path ); ?>
								&nbsp;·&nbsp;
								<?php
								$labels = [
									'managed' => __( 'Downloaded by this plugin', 'product-reels' ),
									'manual'  => __( 'Manual path (settings below)', 'product-reels' ),
									'system'  => __( 'System installation', 'product-reels' ),
								];
								echo esc_html( $labels[ $source ] ?? $source );
								?>
							</span>
						</div>
					</div>
				<?php else : ?>
					<div class="pr-status-banner pr-status-banner--error">
						<span class="pr-status-icon">✘</span>
						<div>
							<strong><?php esc_html_e( 'FFmpeg not found', 'product-reels' ); ?></strong>
							<span class="pr-status-meta"><?php esc_html_e( 'Thumbnail and preview generation are currently disabled.', 'product-reels' ); ?></span>
						</div>
					</div>
				<?php endif; ?>

				<!-- One-click downloader -->
				<div class="pr-settings-section">
					<h3><?php esc_html_e( 'Option 1 — Download static binary (recommended for VPS)', 'product-reels' ); ?></h3>
					<?php if ( ! $download_info ) : ?>
						<div class="pr-notice pr-notice--warning">
							<?php
							printf(
								/* translators: %s: server architecture */
								esc_html__( 'Automatic download is not available for this server architecture (%s). Use Option 2 below.', 'product-reels' ),
								esc_html( php_uname( 'm' ) )
							);
							?>
						</div>
					<?php elseif ( ! $bin_writable ) : ?>
						<div class="pr-notice pr-notice--warning">
							<?php
							printf(
								/* translators: %s: directory path */
								esc_html__( 'The uploads directory is not writable. Please check permissions on: %s', 'product-reels' ),
								'<code>' . esc_html( $bin_dir ) . '</code>'
							);
							?>
						</div>
					<?php else : ?>
						<p class="pr-settings-desc">
							<?php
							printf(
								/* translators: 1: architecture label, 2: download URL host */
								esc_html__( 'A static FFmpeg build for %1$s will be downloaded from %2$s and stored in your uploads folder. The download is ~40 MB and may take a minute.', 'product-reels' ),
								'<strong>' . esc_html( $download_info['label'] ) . '</strong>',
								'<code>johnvansickle.com</code>'
							);
							?>
						</p>
						<p class="pr-settings-desc pr-muted">
							<?php
							printf(
								/* translators: %s: target path */
								esc_html__( 'Binary will be saved to: %s', 'product-reels' ),
								'<code>' . esc_html( $managed_path ) . '</code>'
							);
							?>
						</p>
						<div class="pr-downloader-actions">
							<?php if ( ! $managed_exists ) : ?>
								<button type="button" id="pr_download_ffmpeg_btn" class="button button-primary button-large"
									data-nonce="<?php echo esc_attr( wp_create_nonce( 'product_reels_admin' ) ); ?>">
									⬇️ <?php esc_html_e( 'Download FFmpeg to this server', 'product-reels' ); ?>
								</button>
							<?php else : ?>
								<span class="pr-managed-ok">
									✔ <?php esc_html_e( 'Plugin-managed binary installed.', 'product-reels' ); ?>
								</span>
								<button type="button" id="pr_download_ffmpeg_btn" class="button"
									data-nonce="<?php echo esc_attr( wp_create_nonce( 'product_reels_admin' ) ); ?>">
									🔄 <?php esc_html_e( 'Re-download / update', 'product-reels' ); ?>
								</button>
								<button type="button" id="pr_remove_ffmpeg_btn" class="button pr-btn-danger"
									data-nonce="<?php echo esc_attr( wp_create_nonce( 'product_reels_admin' ) ); ?>">
									🗑 <?php esc_html_e( 'Remove managed binary', 'product-reels' ); ?>
								</button>
							<?php endif; ?>
						</div>

						<!-- Progress UI (hidden until download starts) -->
						<div id="pr_download_progress" style="display:none; margin-top:16px">
							<div class="pr-progress-bar-wrap">
								<div class="pr-progress-bar" id="pr_progress_bar"></div>
							</div>
							<p id="pr_download_status" class="pr-muted"></p>
						</div>
					<?php endif; ?>
				</div>

				<!-- Manual path -->
				<div class="pr-settings-section">
					<h3><?php esc_html_e( 'Option 2 — Manual path', 'product-reels' ); ?></h3>
					<p class="pr-settings-desc">
						<?php esc_html_e( 'If FFmpeg is already installed on the server (e.g. via apt/yum), enter the full path to the binary here.', 'product-reels' ); ?>
					</p>
					<form method="post" action="options.php">
						<?php settings_fields( 'product_reels_settings' ); ?>
						<table class="form-table" role="presentation">
							<tr>
								<th scope="row">
									<label for="product_reels_ffmpeg_path"><?php esc_html_e( 'FFmpeg Binary Path', 'product-reels' ); ?></label>
								</th>
								<td>
									<input type="text" id="product_reels_ffmpeg_path" name="product_reels_ffmpeg_path"
										value="<?php echo esc_attr( get_option( 'product_reels_ffmpeg_path', '' ) ); ?>"
										class="regular-text" placeholder="/usr/bin/ffmpeg">
									<p class="description">
										<?php esc_html_e( 'Leave blank to auto-detect. The managed binary (Option 1) always takes priority over this field.', 'product-reels' ); ?>
									</p>
								</td>
							</tr>
						</table>
						<?php submit_button( __( 'Save Path', 'product-reels' ) ); ?>
					</form>
				</div>
			</div><!-- /.pr-settings-card -->

			<!-- ================================================================
			     Theme integration card
			     ============================================================ -->
			<div class="pr-settings-card">
				<h2><?php esc_html_e( 'Theme Integration', 'product-reels' ); ?></h2>
				<p><?php esc_html_e( 'Call the following function anywhere in your theme template or page builder PHP block to render the reels carousel:', 'product-reels' ); ?></p>
				<pre class="pr-code-block">&lt;?php product_reels_render_section(); ?&gt;</pre>
				<p class="pr-settings-desc"><?php esc_html_e( 'Reels are ordered by Menu Order (drag to reorder in the admin list) then by publish date.', 'product-reels' ); ?></p>
			</div>

			<!-- ================================================================
			     System info card
			     ============================================================ -->
			<div class="pr-settings-card">
				<h2><?php esc_html_e( 'System Info', 'product-reels' ); ?></h2>
				<table class="pr-sysinfo-table">
					<tr><th><?php esc_html_e( 'Plugin version', 'product-reels' ); ?></th><td><code><?php echo esc_html( PRODUCT_REELS_VERSION ); ?></code></td></tr>
					<tr><th><?php esc_html_e( 'PHP version', 'product-reels' ); ?></th><td><code><?php echo esc_html( PHP_VERSION ); ?></code></td></tr>
					<tr><th><?php esc_html_e( 'Server OS', 'product-reels' ); ?></th><td><code><?php echo esc_html( php_uname( 's' ) . ' ' . php_uname( 'm' ) ); ?></code></td></tr>
					<tr><th><?php esc_html_e( 'FFmpeg status', 'product-reels' ); ?></th>
						<td><?php echo $has_ffmpeg
							? '<span style="color:#0a7227">✔ ' . esc_html( $active_path ) . '</span>'
							: '<span style="color:#d63638">✘ ' . esc_html__( 'Not found', 'product-reels' ) . '</span>'; ?></td></tr>
					<tr><th><?php esc_html_e( 'exec() available', 'product-reels' ); ?></th>
						<td><?php echo function_exists( 'exec' ) ? '<span style="color:#0a7227">✔ ' . esc_html__( 'Yes', 'product-reels' ) . '</span>' : '<span style="color:#d63638">✘ ' . esc_html__( 'No (disabled by host)', 'product-reels' ) . '</span>'; ?></td></tr>
					<tr><th><?php esc_html_e( 'Bin directory', 'product-reels' ); ?></th>
						<td><code><?php echo esc_html( $bin_dir ); ?></code>
						<?php if ( $bin_writable ) : ?>
							<span style="color:#0a7227"> ✔ <?php esc_html_e( 'Writable', 'product-reels' ); ?></span>
						<?php else : ?>
							<span style="color:#d63638"> ✘ <?php esc_html_e( 'Not writable', 'product-reels' ); ?></span>
						<?php endif; ?></td></tr>
					<tr><th><?php esc_html_e( 'WooCommerce', 'product-reels' ); ?></th>
						<td><?php echo function_exists( 'wc_get_product' )
							? '<span style="color:#0a7227">✔ ' . esc_html__( 'Active', 'product-reels' ) . '</span>'
							: '<span style="color:#d63638">✘ ' . esc_html__( 'Not active', 'product-reels' ) . '</span>'; ?></td></tr>
				</table>
			</div>

		</div><!-- /.wrap -->
		<?php
	}

	/* -----------------------------------------------------------------------
	 * AJAX: Download FFmpeg static binary
	 * -------------------------------------------------------------------- */
	public function ajax_download_ffmpeg(): void {
		check_ajax_referer( 'product_reels_admin', 'nonce' );

		if ( ! current_user_can( 'manage_options' ) ) {
			wp_send_json_error( [ 'message' => __( 'Permission denied.', 'product-reels' ) ] );
		}

		$download_info = product_reels_ffmpeg_download_info();
		if ( ! $download_info ) {
			wp_send_json_error( [ 'message' => __( 'Automatic download is not supported for this server architecture.', 'product-reels' ) ] );
		}

		// Ensure bin directory exists.
		$bin_dir = product_reels_bin_dir();
		if ( ! is_dir( $bin_dir ) ) {
			wp_mkdir_p( $bin_dir );
			file_put_contents( $bin_dir . '/.htaccess', "Order deny,allow\nDeny from all\n" );
		}

		if ( ! is_writable( $bin_dir ) ) {
			wp_send_json_error( [ 'message' => sprintf(
				/* translators: %s: directory path */
				__( 'Directory is not writable: %s', 'product-reels' ),
				$bin_dir
			) ] );
		}

		// This is a blocking call — JS should display a spinner before triggering it.
		$this->ajax_download_ffmpeg_do();
	}

	/**
	 * Second phase: blocking download + extraction.
	 * JS calls this after the first ack so the UI can show a spinner.
	 */
	public function ajax_download_ffmpeg_do(): void {
		check_ajax_referer( 'product_reels_admin', 'nonce' );

		if ( ! current_user_can( 'manage_options' ) ) {
			wp_send_json_error( [ 'message' => __( 'Permission denied.', 'product-reels' ) ] );
		}

		// Increase time limit — large file download can take a while.
		if ( function_exists( 'set_time_limit' ) ) {
			@set_time_limit( 300 );
		}

		$download_info = product_reels_ffmpeg_download_info();
		if ( ! $download_info ) {
			wp_send_json_error( [ 'message' => __( 'Unsupported architecture.', 'product-reels' ) ] );
		}

		$bin_dir = product_reels_bin_dir();
		if ( ! is_dir( $bin_dir ) ) {
			wp_mkdir_p( $bin_dir );
			file_put_contents( $bin_dir . '/.htaccess', "Order deny,allow\nDeny from all\n" );
		}

		$tarball = $bin_dir . '/ffmpeg-static.tar.xz';

		// Download via WP HTTP (handles SSL, proxies, etc.).
		$response = wp_remote_get( $download_info['url'], [
			'timeout'  => 300,
			'stream'   => true,
			'filename' => $tarball,
		] );

		if ( is_wp_error( $response ) ) {
			wp_send_json_error( [ 'message' => $response->get_error_message() ] );
		}

		$code = wp_remote_retrieve_response_code( $response );
		if ( $code !== 200 ) {
			wp_send_json_error( [ 'message' => sprintf( __( 'Download failed (HTTP %d).', 'product-reels' ), $code ) ] );
		}

		if ( ! file_exists( $tarball ) || filesize( $tarball ) < 1024 * 1024 ) {
			wp_send_json_error( [ 'message' => __( 'Downloaded file appears corrupt or too small.', 'product-reels' ) ] );
		}

		// Extract only the ffmpeg binary from the tarball.
		// The archive structure is: ffmpeg-*-static/ffmpeg
		$binary_dest = product_reels_managed_binary();
		$cmd = sprintf(
			'tar -xJf %s --wildcards --no-anchored "ffmpeg" -O > %s 2>&1',
			escapeshellarg( $tarball ),
			escapeshellarg( $binary_dest )
		);
		$output = [];
		$return_code = 0;
		exec( $cmd, $output, $return_code );

		// Clean up tarball regardless.
		@unlink( $tarball );

		if ( $return_code !== 0 || ! file_exists( $binary_dest ) || filesize( $binary_dest ) < 1024 * 100 ) {
			wp_send_json_error( [
				'message' => __( 'Extraction failed. The tar command may not support .xz on this server.', 'product-reels' )
					. ( $output ? ' ' . implode( ' ', $output ) : '' ),
			] );
		}

		// Make executable.
		chmod( $binary_dest, 0755 );

		// Verify it runs.
		$ver = [];
		exec( escapeshellarg( $binary_dest ) . ' -version 2>&1', $ver );
		$version_line = $ver[0] ?? '';

		// Store the path so detection picks it up immediately.
		// (The managed path check in product_reels_ffmpeg_path() handles this,
		//  but clearing the static cache ensures the settings page reflects it.)
		wp_send_json_success( [
			'message' => sprintf(
				/* translators: %s: ffmpeg version string */
				__( 'FFmpeg installed successfully! %s', 'product-reels' ),
				$version_line ? '(' . esc_html( $version_line ) . ')' : ''
			),
			'path'    => $binary_dest,
		] );
	}

	/* -----------------------------------------------------------------------
	 * AJAX: Remove managed FFmpeg binary
	 * -------------------------------------------------------------------- */
	public function ajax_remove_ffmpeg(): void {
		check_ajax_referer( 'product_reels_admin', 'nonce' );

		if ( ! current_user_can( 'manage_options' ) ) {
			wp_send_json_error( [ 'message' => __( 'Permission denied.', 'product-reels' ) ] );
		}

		$managed = product_reels_managed_binary();
		if ( file_exists( $managed ) ) {
			unlink( $managed );
		}
		// Also remove the htaccess we created.
		$htaccess = product_reels_bin_dir() . '/.htaccess';
		if ( file_exists( $htaccess ) ) {
			@unlink( $htaccess );
		}

		wp_send_json_success( [ 'message' => __( 'Managed FFmpeg binary removed.', 'product-reels' ) ] );
	}
}

/* =========================================================================
 * Front-end render function
 * ====================================================================== */
function product_reels_render_section(): void {
	$reels = new WP_Query( [
		'post_type'      => 'product_reel',
		'posts_per_page' => 20,
		'orderby'        => [ 'menu_order' => 'ASC', 'date' => 'DESC' ],
	] );

	if ( ! $reels->have_posts() ) {
		return;
	}
	?>
	<section class="reels-section" id="reels">
		<div class="reels-wrap">
			<button class="carousel-control carousel-control--prev reels-control--prev" type="button" aria-label="<?php esc_attr_e( 'Previous reels', 'product-reels' ); ?>">
				<span aria-hidden="true">‹</span>
			</button>
			<div class="reels-grid" tabindex="0" role="list">
				<?php while ( $reels->have_posts() ) :
					$reels->the_post();
					$post_id = get_the_ID();

					$source         = get_post_meta( $post_id, '_pr_video_source', true );
					$video_url      = '';
					if ( $source === 'upload' ) {
						$att_id    = absint( get_post_meta( $post_id, '_pr_video_attachment_id', true ) );
						$video_url = $att_id ? wp_get_attachment_url( $att_id ) : '';
					} else {
						$video_url = get_post_meta( $post_id, '_pr_video_url', true );
					}

					if ( ! $video_url ) {
						continue;
					}

					$thumb_id       = absint( get_post_meta( $post_id, '_pr_thumbnail_id', true ) );
					$thumb_url      = $thumb_id ? wp_get_attachment_url( $thumb_id ) : '';
					$preview_enabled = get_post_meta( $post_id, '_pr_preview_enabled', true );
					$preview_id     = absint( get_post_meta( $post_id, '_pr_preview_attachment_id', true ) );
					$preview_url    = ( $preview_enabled && $preview_id ) ? wp_get_attachment_url( $preview_id ) : '';

					$product_id     = absint( get_post_meta( $post_id, '_pr_product_id', true ) );
					$linked_product = $product_id && function_exists( 'wc_get_product' ) ? wc_get_product( $product_id ) : null;
					?>
					<article class="reel-card" role="listitem"
						data-full-src="<?php echo esc_url( $video_url ); ?>">
						<div class="reel-video" data-full-src="<?php echo esc_url( $video_url ); ?>">
							<?php if ( $preview_url ) : ?>
								<video class="reel-video__preview"
									data-full-src="<?php echo esc_url( $video_url ); ?>"
									src="<?php echo esc_url( $preview_url ); ?>"
									<?php if ( $thumb_url ) : ?>poster="<?php echo esc_url( $thumb_url ); ?>"<?php endif; ?>
									autoplay muted loop playsinline></video>
							<?php else : ?>
								<video class="reel-video__preview"
									data-full-src="<?php echo esc_url( $video_url ); ?>"
									<?php if ( $thumb_url ) : ?>poster="<?php echo esc_url( $thumb_url ); ?>"<?php endif; ?>
									muted loop playsinline></video>
							<?php endif; ?>
						</div>
						<?php if ( $linked_product ) : ?>
							<a href="<?php echo esc_url( get_permalink( $product_id ) ); ?>" class="reel-product">
								<?php echo $linked_product->get_image( 'thumbnail' ); ?>
								<div class="reel-product-info">
									<strong><?php echo esc_html( $linked_product->get_name() ); ?></strong>
									<span><?php echo wp_kses_post( $linked_product->get_price_html() ); ?></span>
								</div>
							</a>
						<?php endif; ?>
					</article>
				<?php endwhile; wp_reset_postdata(); ?>
			</div>
			<button class="carousel-control carousel-control--next reels-control--next" type="button" aria-label="<?php esc_attr_e( 'Next reels', 'product-reels' ); ?>">
				<span aria-hidden="true">›</span>
			</button>
		</div>
	</section>
	<?php
}

new Product_Reels_Plugin();